version: '3.3'

networks:
  monitor-net:
    driver: bridge

services:

  fluentbit:
    image: fluent/fluent-bit
    container_name: fluentbit
    volumes:
      - $PWD/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    restart: unless-stopped
    ports:
      - "4318:4318"

    networks:
      - monitor-net

  demoapp:
    image: kduchagaslima/demo-app:opentelemetry-fluentbit 
    container_name: demo-app
    depends_on:
      - fluentbit
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://fluentbit:4318/
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      #- OTEL_IMR_EXPORT_INTERVAL=10000
    networks:
      - monitor-net
